### ISSUE TITLE
Speak the code-week 2 exercice

### ISSUE THREAD

**Issue by Juliebou** [Juliebou/components-on-a-grid#1]
@thatkidmadrid

Here is my mp4 file.
thank you,
Julie Boucher

https://user-images.githubusercontent.com/76826683/134358085-910a0185-cd3e-46cd-9a62-d0ffa32b5151.mp4

**Comment by thatkidmadrid** [comment]
Great!
Easy to follow; I can tell by the way you wrote your stylesheet and the way you read it back that you know your stuff 👍
